{% set table_name = ti.xcom_pull(task_ids='get_dag_configuration')['mysql_table_name'] %}

CREATE TABLE IF NOT EXISTS {{ table_name }} (
    id INT AUTO_INCREMENT PRIMARY KEY,
    `index` INT,
    track_id VARCHAR(255),
    artists TEXT,
    album_name TEXT,
    track_name TEXT,
    popularity INT,
    duration_ms INT,
    explicit BOOLEAN,
    danceability FLOAT,
    energy FLOAT,
    `key` INT,
    loudness FLOAT,
    mode INT,
    speechiness FLOAT,
    acousticness FLOAT,
    instrumentalness FLOAT,
    liveness FLOAT,
    valence FLOAT,
    tempo FLOAT,
    time_signature INT,
    track_genre VARCHAR(255),
    ingestion_timestamp DATETIME,
    source_identifier VARCHAR(50),
    batch_identifier VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_track_id (track_id),
    INDEX idx_ingestion_timestamp (ingestion_timestamp),
    INDEX idx_batch_identifier (batch_identifier),
    INDEX idx_ingestion_id (ingestion_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;